# Pipeline

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('dummy_data_fitur1 (3).csv')

In [ ]:
data

company_name              company_pic  \
0                    Tribakti Inspektama         Lasmanto Pratiwi   
1                   Bank Bukopin Syariah     Puti Gina Napitupulu   
2                   Bank Bukopin Syariah  Karna Purwanti, S.I.Kom   
3                       Kementrian Agama            Tania Yolanda   
4                                  M3kom        Zaenab Anggriawan   
...                                  ...                      ...   
4995                          UD Waskita        Harsaya Budiyanto   
4996                           CV Astuti        Farah Pudjiastuti   
4997                PD Uyainah Budiyanto    Dt. Daliman Kusmawati   
4998           Perum Megantara Handayani             Tasnim Utama   
4999  PT Lailasari Suryono (Persero) Tbk              Vera Kusumo   

                                        company_address        company_phone  \
0     Jalan Cihampelas No. 282\nPontianak, Kalimanta...   +62 (183) 655 1415   
1       Jalan Tubagus Ismail No. 02\nSukabumi, BB 74318       (097) 773 7113   
2       Gg. Pelajar Pejuang No. 660\nJambi, Jambi 60449  +62 (0801) 007-5669   
3                  Jl. Cihampelas No. 8\nTual, ST 59647    +62-0247-253-2150   
4       Gang Moch. Ramdan No. 083\nPayakumbuh, SS 13214       (025) 406 2520   
...                                                 ...                  ...   
4995   Jalan W.R. Supratman No. 9\nDenpasar, Riau 71681      +62-86-249-0929   
4996      Gg. Moch. Toha No. 70\nSungai Penuh, KT 01086   +62 (047) 599 4345   
4997      Gg. Surapati No. 472\nBanjarmasin, Bali 48281  +62 (0329) 186-5208   
4998  Jalan Pasir Koja No. 498\nPurwokerto, Jawa Tim...    +62 (37) 472 3659   
4999   Gang W.R. Supratman No. 92\nSawahlunto, SB 49072   +62 (074) 774-4679   

                        company_email  \
0        muhammadnasyidah@example.org   
1           januarkamaria@example.net   
2               rprasetyo@example.net   
3          iswahyudiraisa@example.net   
4               mulyono67@example.com   
...                               ...   
4995  simanjuntakgamblang@example.org   
4996              johan40@example.org   
4997        fitriapratiwi@example.com   
4998            darmaji97@example.org   
4999          wibowohesti@example.com   

                                         training_topic  \
0     Teknik Analisa Big Data untuk Memaksimalkan Ma...   
1     Teknik Penjualan yang Efektif di Era Covid-19 ...   
2     Mengelola Tim Penjualan Di Era Covid - 19 & WF...   
3     Marketing Support & Sales Admin Development Pr...   
4     Akuisisi Produk Financial Services Melalui Dig...   
...                                                 ...   
4995  Akuntansi dan Keuangan Perbankan bagi Executiv...   
4996                     Professional Digital Marketing   
4997  Understanding Millenials - Managing for High P...   
4998  Perencanaan, Audit & Analisa Kebutuhan Keuanga...   
4999                    Compensation & Benefit Analysis   

            training_category    training_type              company_field  \
0           Sales & Marketing  Online Training      Energi dan Lingkungan   
1           Sales & Marketing  Online Training  Transportasi dan Logistik   
2           Sales & Marketing  Online Training      Energi dan Lingkungan   
3           Sales & Marketing  Online Training  Pariwisata dan Perhotelan   
4           Sales & Marketing  Online Training  Transportasi dan Logistik   
...                       ...              ...                        ...   
4995      Credit & Collection  Online Training  Transportasi dan Logistik   
4996      Credit & Collection  Public Training                     Retail   
4997      Credit & Collection  Online Training                   Keuangan   
4998  Office & Administration  Public Training  Transportasi dan Logistik   
4999  Office & Administration  Public Training    Properti dan Real Estat   

     company_size  ...  communication_channel  purchasing_time_patterns  \
0           Kecil  ...              

In [ ]:
import pandas as pd
import numpy as np
import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, auc
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [ ]:
df = pd.DataFrame(data)

# Pilih fitur-fitur yang ingin digunakan
selected_features = ['training_category', 'training_type', 'company_field',
                     'company_size', 'training_price', 'training_session',
                     'number_of_participants', 'communication_channel',
                     'purchasing_time_patterns', 'payment_total',
                     'payment_method', 'durations', 'ratings', 'feedbacks']

# Memisahkan data berdasarkan fitur yang dipilih
X = df[selected_features]
y = df['sales_pipeline']

# Definisikan transformer untuk masing-masing tipe fitur
numeric_features = ['training_price', 'training_session',  'number_of_participants',
                    'payment_total', 'durations', 'ratings']

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_features = ['training_category', 'training_type', 'company_field',
                        'company_size', 'communication_channel',
                        'purchasing_time_patterns', 'payment_method',  'feedbacks']

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())
])

# Gabungkan transformers menggunakan ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Gabungkan preprocessor dengan model klasifikasi dalam pipeline
pipeline_status = Pipeline(steps=[('preprocessor', preprocessor),
                           ('classifier', RandomForestClassifier())])

# Bagi data menjadi data pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Latih pipeline pada data pelatihan
pipeline_status.fit(X_train, y_train)

# Prediksi dengan pipeline
y_pred = pipeline_status.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

# Tampilkan data nilai prediksi dan nilai seharusnya
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print("Data Nilai Prediksi dan Nilai Seharusnya:")
print(results)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Laporan Klasifikasi
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 0.986
Data Nilai Prediksi dan Nilai Seharusnya:
     Actual Predicted
1501     L2        L2
2586     L2        L2
2653     L1        L1
1055     L1        L1
705      L2        L2
...     ...       ...
4711     L2        L2
2313     L2        L2
3214     L3        L3
2732     L2        L2
1926     L2        L2

[1000 rows x 2 columns]
Confusion Matrix:
[[247   2   0   0]
 [  0 498   5   0]
 [  0   6 202   1]
 [  0   0   0  39]]
Classification Report:
              precision    recall  f1-score   support

          L1       1.00      0.99      1.00       249
          L2       0.98      0.99      0.99       503
          L3       0.98      0.97      0.97       209
          L4       0.97      1.00      0.99        39

    accuracy                           0.99      1000
   macro avg       0.98      0.99      0.99      1000
weighted avg       0.99      0.99      0.99      1000



In [ ]:
pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.1
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.13.1
backcall                         0.2.0
beautifulsoup4                   4.11.2
bidict                           0.22.1
b

# Saving Model

In [ ]:
# Simpan model ke dalam file
joblib.dump(pipeline_status, 'pipeline_status.joblib')
loaded_model_pipeline_status = joblib.load('pipeline_status.joblib')

In [ ]:
!pip install pycaret

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 484.7/484.7 kB 7.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 8.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 11.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 90.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 86.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.5/160.5 kB 19.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 13.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 39.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 75.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 67.3 MB/s e

# Pycaret

In [ ]:
from pycaret.classification import *

In [ ]:
from pycaret.datasets import get_data
dataset = get_data('dummy_data_fitur1 (3)')  # Ganti 'dataset_name' dengan nama dataset Anda

# Inisialisasi setup
clf1 = setup(data = dataset, target = 'sales_pipeline')  # Ganti 'target_column' dengan nama kolom target Anda


company_name              company_pic  \
0   Tribakti Inspektama         Lasmanto Pratiwi   
1  Bank Bukopin Syariah     Puti Gina Napitupulu   
2  Bank Bukopin Syariah  Karna Purwanti, S.I.Kom   
3      Kementrian Agama            Tania Yolanda   
4                 M3kom        Zaenab Anggriawan   

                                     company_address        company_phone  \
0  Jalan Cihampelas No. 282\nPontianak, Kalimanta...   +62 (183) 655 1415   
1    Jalan Tubagus Ismail No. 02\nSukabumi, BB 74318       (097) 773 7113   
2    Gg. Pelajar Pejuang No. 660\nJambi, Jambi 60449  +62 (0801) 007-5669   
3               Jl. Cihampelas No. 8\nTual, ST 59647    +62-0247-253-2150   
4    Gang Moch. Ramdan No. 083\nPayakumbuh, SS 13214       (025) 406 2520   

                  company_email  \
0  muhammadnasyidah@example.org   
1     januarkamaria@example.net   
2         rprasetyo@example.net   
3    iswahyudiraisa@example.net   
4         mulyono67@example.com   

                                      training_topic  training_category  \
0  Teknik Analisa Big Data untuk Memaksimalkan Ma...  Sales & Marketing   
1  Teknik Penjualan yang Efektif di Era Covid-19 ...  Sales & Marketing   
2  Mengelola Tim Penjualan Di Era Covid - 19 & WF...  Sales & Marketing   
3  Marketing Support & Sales Admin Development Pr...  Sales & Marketing   
4  Akuisisi Produk Financial Services Melalui Dig...  Sales & Marketing   

     training_type              company_field company_size  ...  \
0  Online Training      Energi dan Lingkungan        Kecil  ...   
1  Online Training  Transportasi dan Logistik     Menengah  ...   
2  Online Training      Energi dan Lingkungan     Menengah  ...   
3  Online Training  Pariwisata dan Perhotelan        Besar  ...   
4  Online Training  Transportasi dan Logistik     Menengah  ...   

   communication_channel  purchasing_time_patterns  payment_total  \
0                  Email                    Diskon      138132950   
1                  Email                     Bulan      198347094   
2               Linkedin                     Bulan      299626851   
3               Facebook                    Diskon      364423884   
4                     WA             Hari Spesifik      195849846   

  payment_method durations                                     training_dates  \
0          Tunai        26  DatetimeIndex(['2022-01-01', '2022-01-02', '20...   
1            ATM        10  DatetimeIndex(['2022-01-01', '2022-01-02', '20...   
2            ATM        16  DatetimeIndex(['2022-01-01', '2022-01-02', '20...   
3            ATM         5  DatetimeIndex(['2022-01-01', '2022-01-02', '20...   
4       E-Wallet        29  DatetimeIndex(['2022-01-01', '2022-01-02', '20...   

   ratings feedbacks  sales_pipeline        sales_person  
0        4     Buruk              L1        Agnes Irawan  
1       10     Bagus              L3         Qori Aryani  
2       10     Bagus              L3  dr. Kasiyah Rajasa  
3        4     Buruk              L2  R.A. Cici Wibisono  
4        2     Buruk              L1     Amalia Pradipta  

[5 rows x 24 columns]

In [ ]:
# Membuat model
model = create_model('rf')

# Membandingkan model
compare_models()


Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=1963, solver='auto',
                tol=0.0001)

In [ ]:
tuned_model = tune_model(model)

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits


Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).
